bypass_zone:
  name: Bypass Zone
  description: Bypass or unbypass a zone on the alarm panel.
  target:
    entity:
      integration: crow_shepherd
      domain: alarm_control_panel
  fields:
    zone_id:
      name: Zone ID
      description: The ID of the zone to bypass.
      required: true
      example: "1"
      selector:
        text:
    bypass:
      name: Bypass
      description: True to bypass the zone, false to unbypass.
      required: true
      default: true
      selector:
        boolean:

trigger_camera_snapshot:
  name: Trigger Camera Snapshot
  description: Trigger a PIR camera zone to take a new snapshot.
  target:
    entity:
      integration: crow_shepherd
      domain: alarm_control_panel
  fields:
    zone_id:
      name: Zone ID
      description: The ID of the camera zone to trigger.
      required: true
      example: "1"
      selector:
        text:
